### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by briangordon** [dmp1ce/joinmarket-DOCKERFILE#1]
Hi-

This was very useful - thanks! I ran into a couple of things that you might consider including in the readme.

First, entrypoint.sh won't work if you're running docker commands as root. The `usermod` command will fail because the root user already exists in the container. It was simple enough to follow the instructions at https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user in order to run docker commands as my unprivileged user. 

And secondly, it might be nice to have a small section on setting up Bitcoin Core in another container and enabling communication between them. It took me a couple of hours to piece the docker stuff together, and there's a lot of configuration that's not really relevant for exclusive JoinMarket use, so I think it makes some sense to have the information here. The following setup worked for me, after modifying your `jm` script to include `--network bitcoin-net` in its docker run command:

```
docker network create --subnet=172.19.0.0/16 bitcoin-net
docker run -d --name bitcoin-server -v bitcoin-vol:/home/bitcoin/.bitcoin --network bitcoin-net --restart unless-stopped ruimarinho/bitcoin-core -printtoconsole -rpcuser=brian -rpcpassword=password -rpcallowip=172.19.0.0/16 -rpcbind=0.0.0.0 -prune=1024
```

You can run bitcoin-cli commands against bitcoind over the JSON-RPC port like this:

```
docker run -it --rm --network bitcoin-net ruimarinho/bitcoin-core bitcoin-cli -rpcconnect=bitcoin-server -rpcuser=brian -rpcpassword=password help
```

And the relevant section of my joinmarket.cfg has:

```
network = mainnet
rpc_host = bitcoin-server
rpc_port = 8332
rpc_user = brian
rpc_password = password
#rpc_wallet_file = 
```

(AFAICT there's no need for a strong password. You have to be able to talk to docker in order to get on the bitcoin-net bridge network, and docker can see everything going on inside the container anyway.)

Thanks again!

**Comment by dmp1ce** [comment]
Thank you for looking at the Dockerfile configuration. I never considered people would run the container as root, but that makes sense that some people would. I can modify the script so it still works.

I think you are right about the bitcoin password, unless you are exposing Bitcoin Core to an application outside of Docker.

BTW, I have a Docker Compose project where I try to build on top of Tor + Bitcoin Core + LND. It includes JoinMarket as an override.

https://github.com/dmp1ce/BTC-Privacy-Suite

**Comment by dmp1ce** [comment]
Root users using `sudo` and true root users ought to work using the `jm` script or running docker manually.

15441a367b29c86b6fbb5bdc427103017fbf9fb3
cbaa019eae4fe5871345a0624769307f118a6a7a
