### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by briangordon** [dmp1ce/joinmarket-DOCKERFILE#4]
If it's not too much trouble, could you pick a license and add it to the repo? My employer, and many others, allow contributing to open-source projects - but with no license file or mention in the readme it's impossible to say that this is in fact an open-source project.

**Comment by dmp1ce** [comment]
That is cool your employer is interested in JoinMarket! I usually open my projects up to the public but I forgot to add a LICENSE to this project.

da353476de3ac516845fd7d06d38c0eaddf9ef61
