### ISSUE TITLE
/home/joinmarket is owned by root

### ISSUE THREAD

**Issue by briangordon** [dmp1ce/joinmarket-DOCKERFILE#5]
```
  File "/jm/clientserver/jmclient/jmclient/taker.py", line 756, in make_commitment
    with open("commitments_debug.txt", "wb") as f:
builtins.PermissionError: [Errno 13] Permission denied: 'commitments_debug.txt'
```

It looks like joinmarket kinda leaves debug files sitting in the CWD:

https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/ebd4a82403b45ddc1ff1af8dd82299e6a8c6a696/jmclient/jmclient/taker.py#L756
https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/ebd4a82403b45ddc1ff1af8dd82299e6a8c6a696/jmclient/jmclient/podle.py#L249
https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/ebd4a82403b45ddc1ff1af8dd82299e6a8c6a696/jmclient/jmclient/maker.py#L338

Chowning /home/joinmarket to be owned by joinmarket:joinmarket fixed this for me, though I don't know if you want to handle this differently in the dockerfile.

**Comment by dmp1ce** [comment]
That's too bad. I'm not sure why they are putting those files in `~/` and not `~/.joinmarket`. I'll fix the issue here and create an issue upstream.

**Comment by dmp1ce** [comment]
I created a pull request upstream: https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/593

**Comment by dmp1ce** [comment]
Let me know if this fixes the issue for you. https://github.com/dmp1ce/joinmarket-DOCKERFILE/commit/5c3ec0d34ed2c107e10f4dc7c9ff72a0271aad34

**Comment by briangordon** [comment]
Yeah that's the same change I made locally and it fixed things. Thanks!
